### ISSUE TITLE
links from invoices

### ISSUE THREAD

**Issue by ivardesign** [bitpay/whmcs-plugin#18]
links from invoices (viewing from FF v38.0.1) producing garbled URL's

**Comment by sambohler** [comment]
What links specifically are producing it?

**Comment by ivardesign** [comment]
Sorry for the vague description.

The whmcs customer invoice appears with the BitPay "Pay Now" button, which when clicked, directs to a new page on BitPay.com.  There, a button appears near the top that reads "Pay with Bitcoin."

That is where the trouble is that I'm experiencing.  When clicked, FF reports:
"The address wasn't understood
Firefox doesn't know how to open this address, because one of the following protocols (bitcoin) isn't associated with any program or is not allowed in this context.
You might need to install other software to open this address."

Am I missing something?  I cant tell if it's a problem with the url being passed by the plugin or a bitpay issue, or do I actually need some kind of software on the users system for them to be able to use bitpay/bitcoin?

**Comment by ionux** [comment]
Ah, ok, you're referring to the bitcoin payment URI's.  You will need to have a bitcoin wallet installed on whatever device or computer you're attempting to open those links.  It will register itself as the handler for bitcoin:// type links.  Or you could scan the QR code with your bitcoin wallet.

**Comment by ivardesign** [comment]
Aha!  Thank you so much!
