### ISSUE TITLE
Will not Connect to Mysqyl On WHMCS 6.0

### ISSUE THREAD

**Issue by chedicorn** [bitpay/whmcs-plugin#19]
can you verify this works with WHMCS 6.0 ? 
I'm getting mysqyl errors when customers try to purchase using bitcoin.

I had no issues with WHMCS 5+  

here's errors, 

r:  Class 'WHMCS\Invoice' not found in /home/hosting2/public_html/Client/includes/gatewayfunctions.php on line 0
[09-Jul-2015 00:19:20 UTC] PHP Warning:  include(../../../dbconnect.php): failed to open stream: No such file or directory in /home/hosting2/public_html/Client/modules/gateways/bit-pay/createinvoice.php on line 2
[09-Jul-2015 00:19:20 UTC] PHP Warning:  include(../../../dbconnect.php): failed to open stream: No such file or directory in /home/hosting2/public_html/Client/modules/gateways/bit-pay/createinvoice.php on line 2

**Comment by ionux** [comment]
WHMCS 6 was released just a few days ago.  We're in the process of evaluating the new version.

**Comment by chedicorn** [comment]
Thanks yes I know, well the developers release was out much sooner :)
I've managed to get it almost working here by taking out ../../../dbconnect.php
it seems to want to connect or at least the database errors go away.

anyways it's a must to have this going for us as we have quite the busy website.

would you be able to fix it for a fee?

**Comment by chedicorn** [comment]
Sorry I don't want to break any rules here offering you money I'm obviously new one this website here. But I'll pay anyone who is willing to re-code this script just contact me at offshoreseovps.com
it's pretty important :) just ask for Josh on the caht box.

**Comment by ionux** [comment]
No worries!  We will be releasing the patch for this very soon! :)
