### ISSUE TITLE
Invoice Error 'S'

### ISSUE THREAD

**Issue by werneri** [bitpay/whmcs-plugin#22]
I am trying to setup the WHMCS Plugin with WHMCS 5.3.14

I created an Merchant Account with BitPay and copied the Legacy Key from BitPay to the plugin. My default currency setting in WHMCS is EUR.

When trying to pay for a bill - I get the following error:

[ERROR] In modules/gateways/bitpay/createinvoice.php: Invoice error: 'S'

Thank you in advance for your help.
Werner

**Comment by azhard4int** [comment]
I have been facing the same issue. 

You don't have permission to access /clients/modules/gateways/bit-pay/createinvoice.php on this server. 

Server unable to read htaccess file, denying access to be safe

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

Any help regarding this?

**Comment by ionux** [comment]
@azhard4int That sounds like a file permissions issue.  Ensure that the webserver has permission to read the files and that the files are actually present.

**Comment by werneri** [comment]
It seems to be that the Webserver has no permission problem. But as this is an installation on Windows / IIS - the server does not recognize .htaccess. Maybe this is the problem?

Thank you,
Werner

**Comment by ionux** [comment]
@werneri That's possible!  I'm not as familiar with a Windows hosting environment so I wish I could be of more help specifically with that.  However, a quick Google search turned up this: http://www.iis.net/learn/application-frameworks/install-and-configure-php-applications-on-iis/translate-htaccess-content-to-iis-webconfig
