### ISSUE TITLE
Refunds through API

### ISSUE THREAD

**Issue by chihoko** [bitpay/whmcs-plugin#23]
Is there any reason this module doesn't support refunds through the new Bitpay API?

**Comment by aleitner** [comment]
This plugin is currently using the Version 1 API only, and we have not yet created a WHMCS plugin using the version 2 API. Refunds require a merchant facade token, which can only be received through our Version 2 API, which is accessed using a vastly different and more upgraded library. We're currently working on updating all of our plugins that are still on the Version 1 API to the Version 2 API.
