### ISSUE TITLE
whmcs integration

### ISSUE THREAD

**Issue by nicksid** [bitpay/whmcs-plugin#24]
Hello,

i just install whmcs module but the following error page appears at the final payment page:

The address wasn't understood

Firefox doesn't know how to open this address, because one of the following protocols (bitcoin) isn't associated with any program or is not allowed in this context.
You might need to install other software to open this address.

any help?

thanks
Nick

**Comment by ionux** [comment]
That's not related to the plugin - that is the bitcoin URI on the invoice.  You'll need to install a bitcoin wallet in order to handle those addresses.
