### ISSUE TITLE
related to WHMCS 6.1.1, HTTP 500 error in createinvoice.php

### ISSUE THREAD

**Issue by kleetus** [bitpay/whmcs-plugin#26]
Solution provided by Eno Ennok

The problem was tiny actually. Need to change 1 Word in createinvoice.php and it fixed all issues for me.

originally is in this file code 
include("../../../dbconnect.php");

but that should be changed to this: 
include("../../../init.php");

and its working.

**Comment by emiljoensson** [comment]
Isn't this in createinvoice.php already?

```
if (file_exists('../../../dbconnect.php')) {
    include '../../../dbconnect.php';
} else if (file_exists('../../../init.php')) {
    include '../../../init.php';
```

**Comment by kleetus** [comment]
It looks like it, yes. Thanks for the clarification.
