### ISSUE TITLE
bad error reporting in createinvoice.php

### ISSUE THREAD

**Issue by gaud2029** [bitpay/whmcs-plugin#31]
line 115 of createinvoice.php : 
die('[ERROR] In modules/gateways/bitpay/createinvoice.php: Invoice error: ' . var_export($invoice['error']['message'], true));

there is no 'message' key, the reported error is always just the first letter of the error message.

for example if you have this string in $invoice['error'] "Couldn't resolve test.bitpay.com' , you only get this error message returned: 

[ERROR] In modules/gateways/bitpay/createinvoice.php: Invoice error: 'C'

**Comment by chedicorn** [comment]
IS there any support for this module now? I haven't seen any activity here in sometime. The plugin is out of date and doesn't work with WHMCS anymore at least non of the times I've tried it, and now with the release of WHMCS 7.0 it for sure needs to be updated. Can someone please look into fixing this plugin for us as it really really needs it I'm sure there's many people out there that also need this plugin. This site is added as the main developer on the bitpay.com site.

**Comment by big89** [comment]
Hello, we can work on this professionally. If anyone needs help on this module for WHMCS, then contact us. Thanks

**Comment by big89** [comment]
We have updated the module to work with WHMCS 7. Anyone wants to test it ?

**Comment by MichaelFindlay** [comment]
Would be happy too. You got the WHMCS 7 download.

**Comment by big89** [comment]
We don't have WHMCS 7 available right now to test this module. But we already updated that according to latest version 7 of WHMCS. If you want to use this official module, you can contact us. Thanks !!!

**Comment by chedicorn** [comment]
Yes please make new plugin available as it's nowhere to be seen. Thank you can you make it available on bithub download?

**Comment by big89** [comment]
Anyone wants this module can contact us. Thanks !!!

**Comment by pieterpoorthuis** [comment]
We are working on a fully v7 compatible release. I expect it to be ready in two months from now.

**Comment by zero-master** [comment]
@pieterpoorthuis  any update on WHMCS v7? 

These stats might be good enough to justify development expense: https://www.similarweb.com/website/whmcs.com#overview

WHMCS isn't SaaS, it's a self hosted solution.

Basically, a large chunk of hosting industry uses WHMCS.

**Comment by pieterpoorthuis** [comment]
Our dev team is working on a v6 & v7, PHP5.6 & PHP7 compatible release. I expect a release end of March.

**Comment by big89** [comment]
Official module we already updated, tested and implemented with Whmcs user. They are using it properly already...and important is Whmcs 7 is nothing changed for gateways. Bitpay is very old as compared to Whmcs versions. If users are requesting its update from years, bitpay still needs months. I think they are outsourcing module developer and teaching him bitpay how it works. Then he will develope module.

**Comment by GenIPTV** [comment]
@big89 i need your help for this payment

**Comment by zero-master** [comment]
@big89 please either consider releasing your plugin for either free or stop advertising it on bitpay's official repository. You are helping no one by hawking your solution here.

**Comment by big89** [comment]
Hello, we are not advertising anything here. We only telling bitpay to take
initiative to update it and also informing u all about this update that its
not that much major. If u r looking for free bitpay module then u can only
wait for their official release. We are only helping them who already stuck
with existing module use which was delayed by bitpay.

**Comment by big89** [comment]
@GenIPTV yes we can help u for ur issue.

**Comment by daalien** [comment]
From bitpay support last month:

"I expect a V7 compatible version to be released mid April. "

**Comment by big89** [comment]
We already know that, as bitpay contacted us for this module to update. We are just thinking that if we can update it then why bitpay till not.

**Comment by daalien** [comment]
Perfect. Was just commenting as I was checking this thread last month and also wanted to get Bitcoin going again in our WHMCS setup.

**Comment by pieterpoorthuis** [comment]
We've just committed new code that is WHMCS v7 compatible (tested against WHMCS v7.1.2)

You can download the latest code here: https://github.com/bitpay/whmcs-plugin/archive/master.zip

I will create a release next week (provided no issues are found).
