### ISSUE TITLE
v7 compatible?

### ISSUE THREAD

**Issue by Yzord** [bitpay/whmcs-plugin#34]
I have v7 of WHMCS installed and uploaded the module to modules/gateways. But when i go to Setup-Payments-Payment Gateways i can't find the Bit-Pay module between the others. Is it compatible with v7?

**Comment by chedicorn** [comment]
IS there any support for this module now? I haven't seen any activity here in sometime. The plugin is out of date and doesn't work with WHMCS anymore at least non of the times I've tried it, and now with the release of WHMCS 7.0 it for sure needs to be updated. Can someone please look into fixing this plugin for us as it really really needs it I'm sure there's many people out there that also need this plugin. This site is added as the main developer on the bitpay.com site.

**Comment by big89** [comment]
Hello, we can work on this professionally. If anyone needs help on this module for WHMCS, then contact us. Thanks

**Comment by bStyler** [comment]
We've also appreciate official WHMCS v7 support.

**Comment by big89** [comment]
We can make this module WHMCS v7 compatible. So, anyone wants this module just contact us,, Thanks !!!

**Comment by chedicorn** [comment]
Yes please fix the plugin for us nobody seems to want to do it : ( Thank you!

**Comment by big89** [comment]
Yea we can. But for that you needs to personally contact me and hire me for that if u really wants.

**Comment by chedicorn** [comment]
IT's supposed to be a free plug-in : ( I can't really buy it when bitpay is supposed to provide it for free. 

I don't know why they depend on git-hub society to get it done but it should be done by bitpay and they should hire someone to do it.

**Comment by big89** [comment]
Yea its ok nop. But am working professionally for WHMCS Payment Gateway Modules.

**Comment by big89** [comment]
See what they say - https://github.com/bitpay/whmcs-plugin/issues/36

**Comment by chedicorn** [comment]
Thanks for the post, will be happy to see someone finally fix the plug-in the plugin was actually broken way before the new WHMCS update and nobody would fix it.  I had to change bitcoin processors because I couldn't get the payment gateway to work in WHMCS for bitcoins for bitpay. So I switched to coinpayments and just use an exchange to get my money out now instead. IT's a bit more tedius but ah well it works. so It doesn't even matter really now if the plug-in is fixed to be honest I found another way but we'll see if anyone fixes it first.

**Comment by bStyler** [comment]
I'm still on WHMCS v5 where this module works just fine.

**Comment by big89** [comment]
Yea, but most of the peoples using latest version 7 of WHMCS. So, for this
version, Bitpay module in not compatible as they said. Right !!!

**Comment by chedicorn** [comment]
Yeah but I'm not on WHMCS 5 I always keep the updated version because of the hacks that were presented last year.


PEople can hack into your WHMCS with sending emails to you it's not hard for them to do so


and upload malaware for their google Anaylitics into your header of your site.


This is why I keep it updated.


anyways I hope they fix the plug-in it worked great for about 2 years then it quit.


Now nobody wants to fix the dam thing and bitpay says they supply the plug-in for free but they don't


they put it into open source git-hub. I Guess it's free but it's  a shady way of saying they provide a free plugin for free.


Bitpay should supply and pay a devloper to fix the plugin when it needs updating thats' what should happen : )


________________________________

**Comment by big89** [comment]
I can solve all prblms...anyone wants just contact me...thanks

**Comment by big89** [comment]
We have updated the module to work with WHMCS 7. Anyone wants to test it ?

**Comment by Yzord** [comment]
We want an official plugin. Not a forked one which could not be safe. I do not recommend a forked one to anyone!!

**Comment by big89** [comment]
I have updated this official module only, not any third party plugin. If Bitpay wants to accept this one and can test. Ok

**Comment by pieterpoorthuis** [comment]
Hi Big89, I've sent you an email. Interested in your update.

**Comment by bStyler** [comment]
@pieterpoorthuis and @big89 were you able to make the module work on WHMCS v7?

**Comment by big89** [comment]
Hello,

We already updated this module, just needs to test on WHMCS setup.

We also talked with @pieterpoorthuis <https://github.com/pieterpoorthuis>
about this but I think they are not interested to provide support for this
module.

So, if anyone wants we can work on this and help you at professional level.



Thanks & Regards,

Bhagwan

**Comment by pieterpoorthuis** [comment]
We are working on a fully v7 compatible release. I expect it to be ready in two months from now.

**Comment by bStyler** [comment]
@pieterpoorthuis thank you for your efforts!

Any special reason why it takes 2 months and not shorter?

The module for WHMCS v5 is available and open source and you can reuse most of the code there, with slight adjustments to WHMCS v7.

Thanks again!

**Comment by big89** [comment]
We think that its not take 2 months time to make it WHMCS 7 compatible.
WHMCS having regular updates but Bitpay module not having any updates from
long ago.

As we already updated this official module according to WHMCS 7, but Bitpay
@pieterpoorthuis <https://github.com/pieterpoorthuis> not accepting it to
official release as they don;t have any in-house plugin developer.

Any help will get professionally serviced by us !!!

Thanks

**Comment by pieterpoorthuis** [comment]
It takes time to allocate developers. As indicated above, I expect a fully compatible version to be released by BitPay in two months time.

**Comment by big89** [comment]
Official module we already updated, tested and implemented with Whmcs user. They are using it properly already...and important is Whmcs 7 is nothing changed for gateways. Bitpay is very old as compared to Whmcs versions. If users are requesting its update from years, bitpay still needs months. I think they are outsourcing module developer and teaching him bitpay how it works. Then he will develope module.

**Comment by bStyler** [comment]
Greetings @pieterpoorthuis 

Can you please advise what's the status of the official WHMCS v7 compatible version?
Are you still expecting this to be finished by April 7th?

Many thanks!

**Comment by big89** [comment]
Hello All, We already told that we have updated this module, Tested and
implemented with WHMCS 7.

Bitpay Officials not accepting this as we already recommended them.

so, why they taken this much
Really they assigned this module development to any outsourced developer ?

**Comment by pieterpoorthuis** [comment]
bStyler,

The rework seems less than we anticipated, but we had a delayed start. Overall I expect to have a WHMCS v7 compatible release by mid April

**Comment by big89** [comment]
Now we can understand the seriousness of official Bitpay Payment Module support after a Year. Till awaiting for official updated module, which don't know how much time required for outsourced developer to complete it.

Let's see !!!

**Comment by bStyler** [comment]
@pieterpoorthuis Greetings! Just checking in, can you please share a status update on WHMCS v7 official compatible module for Bitpay?

Many thanks,
