### ISSUE TITLE
404 error reporting in createinvoice.php

### ISSUE THREAD

**Issue by chedicorn** [bitpay/whmcs-plugin#35]
Hi, 

anytime a user uses bitpay module or when we test this module anytime we go to createinvoice.php we get re-directed to a 404 error. Which is strange all other versions of this plug-in worked we checked our cloudflare nothing is blocking us. Any suggestions please?

**Comment by chedicorn** [comment]
IS there any support for this module now? I haven't seen any activity here in sometime. The plugin is out of date and doesn't work with WHMCS anymore at least non of the times I've tried it, and now with the release of WHMCS 7.0 it for sure needs to be updated. Can someone please look into fixing this plugin for us as it really really needs it I'm sure there's many people out there that also need this plugin. This site is added as the main developer on the bitpay.com site.

**Comment by big89** [comment]
Hello, we can work on this professionally. If anyone needs help on this module for WHMCS, then contact us. Thanks

**Comment by big89** [comment]
We have updated the module to work with WHMCS 7. Anyone wants to test it ?

**Comment by pieterpoorthuis** [comment]
We've just committed new code that is WHMCS v7 compatible (tested against WHMCS v7.1.2)

You can download the latest code here: https://github.com/bitpay/whmcs-plugin/archive/master.zip

I will create a release next week (provided no issues are found).
