### ISSUE TITLE
Any Support?

### ISSUE THREAD

**Issue by chedicorn** [bitpay/whmcs-plugin#36]
This plugins hasn't worked in sometime is anyone going to upgrade it?

now we have WHMCS version 7 out I'm sure this is a perfect time to upgrade the bitpay plugin

Thank you.

**Comment by chedicorn** [comment]
IS there any support for this module now? I haven't seen any activity here in sometime. The plugin is out of date and doesn't work with WHMCS anymore at least non of the times I've tried it, and now with the release of WHMCS 7.0 it for sure needs to be updated. Can someone please look into fixing this plugin for us as it really really needs it I'm sure there's many people out there that also need this plugin. This site is added as the main developer on the bitpay.com site.

**Comment by big89** [comment]
Hello, we can work on this professionally. If anyone needs help on this module for WHMCS, then contact us. Thanks

**Comment by licensecart** [comment]
They have probably forgotten about it because WHMCS is useless.

**Comment by pieterpoorthuis** [comment]
We haven't forgotten about WHMCS. Working on getting the right developer resources to make BitPay's WHMCS v7 compatible. I can't give any timelines yet.

**Comment by licensecart** [comment]
But why should you have to, WHMCS charges a load surely they can do their own.

**Comment by chedicorn** [comment]
thank you about time someone answered :) it would be nice to see this module working again. Even the last update of WHMCS the plugin failed at the end of the release. There was some modifications made but it didn't help.

**Comment by pieterpoorthuis** [comment]
We've just committed new code that is WHMCS v7 compatible (tested against WHMCS v7.1.2)

You can download the latest code here: https://github.com/bitpay/whmcs-plugin/archive/master.zip

I will create a release next week (provided no issues are found).
