### ISSUE TITLE
Gateway is not updating the WHMCS Default Payment Method for a client

### ISSUE THREAD

**Issue by bStyler** [bitpay/whmcs-plugin#37]
Hi guys,

The module is currently not updating the "Payment Method" field in the WHMCS client profile upon first payment. This is something that is common within many WHMCS payment gateways.

To be more specific, the 'defaultgateway' column should be set to 'bitpay' for the paying client in the **tblClients** table and it's currently empty, therefore it looks as follows on WHMCS: http://prntscr.com/do2lmi

Can you please fix this issue?

Many thanks,

**Comment by big89** [comment]
Hello, we can work on this professionally. If anyone needs help on this module for WHMCS, then contact us. Thanks

**Comment by big89** [comment]
We have updated the module to work with WHMCS 7. Anyone wants to test it ?

**Comment by chedicorn** [comment]
OF course we want to test it can someone make it available please so everyone can use the working one.

**Comment by big89** [comment]
Anyone wants this module can contact us. Thanks !!!

**Comment by pieterpoorthuis** [comment]
In the newest code tblclients is set: https://github.com/bitpay/whmcs-plugin/archive/master.zip

**Comment by bStyler** [comment]
Thanks for fixing that issue as well @pieterpoorthuis that's much appreciated! We'll test the module soon.

**Comment by MrKaKisen** [comment]
Hi, is this issue fixed?

**Comment by bStyler** [comment]
@MrKaKisen I believe it is fixed in the latest version, yes. Have you experienced that issue on the latest version of WHMCS v7 and the plugin?

**Comment by MrKaKisen** [comment]
@bStyler I haven't tried yet, it should work for whmcs v7.x.x?

**Comment by bStyler** [comment]
@MrKaKisen worked fine on v7.x.x here. Yes. :)

**Comment by MrKaKisen** [comment]
@bStyler I see, thanks! :)
