### ISSUE TITLE
whmcs 7.1 known issue ? 

### ISSUE THREAD

**Issue by gaud2029** [bitpay/whmcs-plugin#38]
I did some testing and I was able to pay an invoice using bitpay and whmcs 7.1. 

I would like to know what are the known issues with this plugins when used with whmcs 7.1  exactly.

**Comment by chedicorn** [comment]
there is no proper invoice created with createinvoice.php it's just re-directed to WHMCS cart page that says 404 error. There should be a bitpay invoice that is created and shown a unique bitcoin address for clients to send money to.  I'm also using cloudflare if this is doing something to it, but I can't see how or why as the plugin has always worked for me up until a couple months ago. This plugin never had any issues now it will not work I believe it's that file but I could be wrong php error reporting doesn't report anything wrong either does WHMCS error reporting.

**Comment by big89** [comment]
Official module we already updated, tested and implemented with Whmcs user. They are using it properly already...and important is Whmcs 7 is nothing changed for gateways. Bitpay is very old as compared to Whmcs versions. If users are requesting its update from years, bitpay still needs months. I think they are outsourcing module developer and teaching him bitpay how it works. Then he will develope module.

**Comment by pieterpoorthuis** [comment]
We've just committed new code that is WHMCS v7 compatible (tested against WHMCS v7.1.2)

You can download the latest code here: https://github.com/bitpay/whmcs-plugin/archive/master.zip

I will create a release next week (provided no issues are found).
