### ISSUE TITLE
WHMCS with Cloudflare SSL

### ISSUE THREAD

**Issue by TechLineX** [bitpay/whmcs-plugin#39]
Dear Support,

if I use the cloudflare SSL, I can't setup the correct link under whmcs settings.

WHMCS System URL has still to be http. -> Cloudflare is redirecting automatically all to https.
If I set the whmcs url to https, I always get the error too many redirects.

But if a customer now creates a invoice, he gets the following error:
[ERROR] In modules/gateways/bitpay/createinvoice.php: Invalid invoice id #0

I think this hang together with http & https

Hope to get help from your side.

**Comment by chedicorn** [comment]
This could have something to do with it your right, I also use cloudflare. But before a couple months ago this never happened and I still had cloudflare so I dunno I think it's the plugin and it's compatibility with WHMCS latest version. There just needs to be a new release.

**Comment by big89** [comment]
I think this is not an issue related with Cloudflare. The issue is bitpay module is not compatible with latest versions of WHMCS.

We have updated that module already. Anyone wants to test it, kindly provide WHMCS setup.

**Comment by TechLineX** [comment]
Updated the Module, all working fine again. Thank you.

**Comment by TechLineX** [comment]
Hi, 

problem is there again.. 

[ERROR] In modules/gateways/bitpay/createinvoice.php: Invalid invoice id #0

**Comment by big89** [comment]
Hello,

Try to understand the problem. We know this error is already there, then
what you updated and what is working fine again ?

This module is useless in WHMCS 7 from long ago.

We already identified the issues in the module and updated according to
WHMCS 7.

Still any one wants to test it in WHMCS 7, let us know.

Thanks

**Comment by daalien** [comment]
How can I get the code to test ? 

I'm getting a 500 on createinvoice.php using this module.

**Comment by big89** [comment]
Hello, we have updated this official module according to WHMCS 7. Also
tested and its working.

You can contact me if you want to Test it.

Thanks !!!

**Comment by daalien** [comment]
I opened a support request directly with bitpay as they still link to what looks to be a deprecated plugin, BUT I don’t see any harm in testing the one you guys have ? 

 

Are you going to release it to github so that it can be reviewed ? Taking a payment module from an “unknown” is a little risky,

 

Thanks,

 

Tom.
