### ISSUE TITLE
WHMCS v7 Support?

### ISSUE THREAD

**Issue by bStyler** [bitpay/whmcs-plugin#43]
Hi guys,

I know that an official Bitpay module for WHMCS v7.1 is in the making.

@pieterpoorthuis once mentioned in another issue that it's due for middle April.

Can we can a status update, please?

We'd love continuing Bitpay as our Bitcoin gateway with WHMCS.

Best wishes,

**Comment by pieterpoorthuis** [comment]
We've just committed new code that is WHMCS v7 compatible (tested against WHMCS v7.1.2)

You can download the latest code here: https://github.com/bitpay/whmcs-plugin/archive/master.zip

I will create a release next week (provided no issues are found).

**Comment by bStyler** [comment]
@pieterpoorthuis Thanks for the exciting update.

1) How things looking 6-7 days after? :) Are there any issues found?
2) Is the plugin also WHMCS v5 compatible of WHMCS v7 only?

**Comment by bStyler** [comment]
Bump for @pieterpoorthuis :)

**Comment by pieterpoorthuis** [comment]
There were two issues reported around creating invoices (displaying "Invalid invoice id #0"), that I could not reproduce yet.

Therefore I've created a release of the current source. Feedback/issue reports are appreciated.

**Comment by bStyler** [comment]
Thanks, @pieterpoorthuis !

**Comment by stefanotto** [comment]
As mentioned in #42 I still experience the "Invalid invoice id #0" issue with the latest plugin version
