### ISSUE TITLE
Approved Volume Limit Exceeded error

### ISSUE THREAD

**Issue by QuatroVPS** [bitpay/whmcs-plugin#46]
Hello Folks,

we've been testing a newly added BitPay gateway to our WHMCS billing system that was configured as per GUIDE.md. At the end of a test process we've received "bitpay invoice error" message in a browser window and email from BitPay stating:
+++++++++++++++++++++++
Approved Volume Limit Exceeded
An invoice for $9.90 could not be created because its value exceeds your current approved volume of $0 per day. This invoice would have put you beyond your daily limit....
+++++++++++++++++++++++
We've checked our account settings with BitPay and saw that it is at Tier 0 with $100/day transactions allowance.

Anyone have an idea what's wrong here and how to approach this?

Thanks

**Comment by pieterpoorthuis** [comment]
Most likely your required Tier is higher than your current approved Tier.

Please login to your BitPay merchant account. You should see a screen asking you to increase your processing volume ("upgrade your Tier")

**Comment by QuatroVPS** [comment]
Hi  pieterpoorthuis,

You were right, I had to upgrade to a higher Tier, the one that is associated with business accounts.

Thanks for your help.
