### ISSUE TITLE
Bitcoin address not available, try again later

### ISSUE THREAD

**Issue by drolfe** [bitpay/whmcs-plugin#49]
Upgraded to 7.5 WHMCS and get the below error when trying to pay invoice with bitpay

` In modules/gateways/bitpay/createinvoice.php: Invoice error: array ( 'type' => 'addressUnavailable', 'message' => 'Bitcoin address not available, try again later', )`

I was using whmcs 6.3 before the upgrade,  I've also upgraded to the latest bitpay module

thanks

**Comment by pieterpoorthuis** [comment]
@drolfe I just tested the latest BitPay plugin (v1.1.3) on WHMCS 7.5.1, and everything works ok for me.

Can you send log files (e.g. apache error logs) to sales-engineering@bitpay.com ?

**Comment by apexstrd** [comment]
@pieterpoorthuis 
We have the same issue, for 1 customer only.
We have tested the module and it works without any issues except for 1 customer.
Please advice.

**Comment by pieterpoorthuis** [comment]
@apexstrd Is the 1 customer using a different currency than all other customers? Can you provide a screenshot and/or logs of the failure?

**Comment by apexstrd** [comment]
We use 1 default currency
![er](https://user-images.githubusercontent.com/40631329/41971839-724ca6b4-7a18-11e8-82e4-3078fc16a2db.png)
We're using whmcs 7.5.1, PHP 7.2.6, Bitpay module vv1.1.3

PHP log error 
[ERROR] In modules/gateways/bitpay/createinvoice.php: Invoice error: array (
  'type' => 'addressUnavailable',
  'message' => 'Bitcoin address not available, try again later',

**Comment by apexstrd** [comment]
@pieterpoorthuis
^^^

**Comment by pieterpoorthuis** [comment]
I've included logging in the v1.1.4 release

Can you update your BitPay plugin, enable module logging (WHMCS admin -> Utilities -> Log -> Modules Log, Enable Debug Logging) and send me the logs?

You can send the logs to sales-engineering@bitpay.com if you want.

**Comment by apexstrd** [comment]
@pieterpoorthuis 
Thanks.
You got mail

**Comment by codyro** [comment]
@pieterpoorthuis We've also sent along the debug API call produced by your patch.

**Comment by pieterpoorthuis** [comment]
Thanks a lot. We found the issue, fixing it server side. I'll put a comment here when the fix is live (eta: end of this week)

**Comment by pieterpoorthuis** [comment]
The issue has been fixed on BitPay's end. It was related to rejecting certain mixed case email addresses. 

All should be good now.

**Comment by KnottStudios** [comment]
The exception is actually misleading in several cases.  The most important of which (for my purposes) is when the sent amount to BitPay = 0, it throws this error rather than advising that the error is that you sent an amount of 0 on invoice creation.
