### ISSUE TITLE
Overpayment issue with BitPay

### ISSUE THREAD

**Issue by devaqto** [bitpay/whmcs-plugin#64]
Hi,

It seems that the BitPay module doesn't provide the correct amount to be paid during checkout. Because of this we had issues that customers paid too much.

Example:
- Customer has an invoice of 100 EUR.
- This invoice is partially paid, for example 20 EUR. So 80 EUR must be paid. (this can happen with overpayments and credits).
- The client wants to pay the invoice using BitPay, but instead of 80 EUR, the BitPay checkout requests 100 EUR to be paid. Which is 20 EUR too much.

We only have this issue with the BitPay module. Other modules are working fine in this scenario.

Thanks!

**Comment by tamerciaga** [comment]
Anyone from BitPay here?

**Comment by thejoshualewis** [comment]
Hi tamerciago,
We'll take a look and see if we can reproduce.

**Comment by tamerciaga** [comment]
@thejoshualewis Hi, is there any update? :)

**Comment by devaqto** [comment]
@thejoshualewis :)

**Comment by devaqto** [comment]
@thejoshualewis are you the only developer at BitPay? We have been waiting for 4 months...

**Comment by thejoshualewis** [comment]
Hello @devaqto ,

Are you using the latest release?  We haven't been able to reproduce, attached is a screenshot with a credit applied before payment, and the final BitPay invoice is the correct total.
<img width="871" alt="screenshot_1" src="https://user-images.githubusercontent.com/392836/93239439-c56e3580-f750-11ea-931f-164c0be073a9.png">

**Comment by devaqto** [comment]
@thejoshualewis the invoice looks correct, but how much did you "pay" using BitPay? The issue was that the payment amount was not equal to the Total of the invoice.

**Comment by thejoshualewis** [comment]
I created a $10 invoice, applied a $3 credit, and my final BitPay payment was $7
