### ISSUE TITLE
An error occurred loading the gateway

### ISSUE THREAD

**Issue by myhostgoi** [bitpay/whmcs-plugin#65]
Hello,
We have an issue during set up this payment gateway. We have 2 different currencies in our whmcs - INR and USD. We have set Convert To For Processing: None, and the bitpay payment gateway not working, it's showing the error: An error occurred loading the gateway. We have changed the processing currency to USD, but still, the same issue remaining. Kindly help to resolve the issue.
Thank You!

**Comment by thejoshualewis** [comment]
Hello,

Can you send screenshots of your payment configuration to integrations@bitpay.com. ?
