### ISSUE TITLE
Support to WHMCS 8.0

### ISSUE THREAD

**Issue by thelaio** [bitpay/whmcs-plugin#70]
Dear support:
I have upgraded the WHMCS 8.0 for security reasons, but I checked that BitPay has support on WHMCS up to V7.x
Do you have updated files for WHMCS version 8.0 or when do they plan on releasing an update to their module?

Many thanks for your help.
Thanks.

**Comment by Orkzed** [comment]
Up!

**Comment by thejoshualewis** [comment]
Hi @thelaio ,

The latest version had a few minor tweaks, but works for both 7 and 8.
https://github.com/bitpay/whmcs-plugin/archive/3.0.1.9.zip

**Comment by Orkzed** [comment]
I use native module in WHMCS 8, it's work. I must upgrade with this? Or continue to use native module in WHMCS 8?

**Comment by thejoshualewis** [comment]
WHMCS has their own version they maintain, ours is @ https://marketplace.whmcs.com/product/4853/ (which is the same as this repo)
