### ISSUE TITLE
IPN is not working

### ISSUE THREAD

**Issue by monovm** [bitpay/whmcs-plugin#72]
ipn is not change status of payment to paid in whmcs

**Comment by thejoshualewis** [comment]
Hi @monovm,

The payment status will change once the invoice has reached a "completed" state.  It requires HTTPS / POST access to your server for the updates to be applied.

**Comment by monovm** [comment]
Hi there bitpay/whmcs-plugin,


Thank you for contacting our support team - we will do our best in assisting you. A support ticket has now been opened upon your request. You will be notified via an emai regarding further process. 


The details of your ticket are shown below.


Subject: Re: [bitpay/whmcs-plugin] IPN is not working (#72)


Priority: Medium


Status: Open


You can view the ticket at any time here:


https://monovm.com/my/viewticket.php?tid=246804&c=1Zw44bs4


Monovm Support Team

**Comment by monovm** [comment]
Hi there bitpay/whmcs-plugin,


Thank you for contacting our support team - we will do our best in assisting you. A support ticket has now been opened upon your request. You will be notified via an emai regarding further process. 


The details of your ticket are shown below.


Subject: Re: [bitpay/whmcs-plugin] IPN is not working (#72)


Priority: Medium


Status: Open


You can view the ticket at any time here:


https://monovm.com/my/viewticket.php?tid=274605&c=fhta97zx


Monovm Support Team

**Comment by monovm** [comment]
This support request has been marked as completed.


We would really appreciate it if you could take a short, blink-of-an-eye short moment to let us know your experience with our support team.


https://monovm.com/my/viewticket.php?tid=274605&c=fhta97zx&feedback=1


Your feedback is extremely valuable to us - it helps us continuously improve.


Incredibly grateful in advance for submitting the feedback!

**Comment by monovm** [comment]
This support request has been marked as completed.


We would really appreciate it if you could take a short, blink-of-an-eye short moment to let us know your experience with our support team.


https://monovm.com/my/viewticket.php?tid=246804&c=1Zw44bs4&feedback=1


Your feedback is extremely valuable to us - it helps us continuously improve.


Incredibly grateful in advance for submitting the feedback!
